import employPhoto from '@/shared/assets/images/employ-photo.png';


export const employeesVariables = {
  salesDepartment: [
    {
      fullname: 'Гротан Роман Анатольевич',
      mail: 'gra@intei-lada.ru',
      phoneNumber: '+7 812 309 42 20',
      jobTitle: 'Руководитель отдела продаж',
      image: employPhoto,
    },
    {
      fullname: 'Андреев Анатолий Геннадьевич',
      mail: 'gra@intei-lada.ru',
      phoneNumber: '+7 812 309 42 20',
      jobTitle: 'Продавец-консультант',
      image: employPhoto,
    },
    {
      fullname: 'Гордиенко Владислав Александрович',
      mail: 'gra@intei-lada.ru',
      phoneNumber: '+7 812 309 42 20',
      jobTitle: 'Руководитель отдела продаж',
      image: employPhoto,
    },
    {
      fullname: 'Голубев Станислав Борисович',
      mail: 'gra@intei-lada.ru',
      phoneNumber: '+7 812 309 42 20',
      jobTitle: 'Консультант по трейд-ин',
      image: employPhoto,
    },
    {
      fullname: 'Костенко Татьяна Викторовна',
      mail: 'gra@intei-lada.ru',
      phoneNumber: '+7 812 309 42 20',
      jobTitle: 'Ассистент отдела продаж',
      image: employPhoto,
    },
    {
      fullname: 'Гордиенко Владислав Александрович',
      mail: 'gra@intei-lada.ru',
      phoneNumber: '+7 812 309 42 20',
      jobTitle: 'Руководитель отдела продаж',
      image: employPhoto,
    },
    {
      fullname: 'Голубев Станислав Борисович',
      mail: 'gra@intei-lada.ru',
      phoneNumber: '+7 812 309 42 20',
      jobTitle: 'Консультант по трейд-ин',
      image: employPhoto,
    },
    {
      fullname: 'Костенко Татьяна Викторовна',
      mail: 'gra@intei-lada.ru',
      phoneNumber: '+7 812 309 42 20',
      jobTitle: 'Ассистент отдела продаж',
      image: employPhoto,
    },
  ],
  serviceDepartment: [
    {
      fullname: 'Гротан Роман Анатольевич',
      mail: 'gra@intei-lada.ru',
      phoneNumber: '+7 812 309 42 20',
      jobTitle: 'Руководитель отдела продаж',
      image: employPhoto,
    },
    {
      fullname: 'Андреев Анатолий Геннадьевич',
      mail: 'gra@intei-lada.ru',
      phoneNumber: '+7 812 309 42 20',
      jobTitle: 'Продавец-консультант',
      image: employPhoto,
    },
    {
      fullname: 'Гордиенко Владислав Александрович',
      mail: 'gra@intei-lada.ru',
      phoneNumber: '+7 812 309 42 20',
      jobTitle: 'Руководитель отдела продаж',
      image: employPhoto,
    },
    {
      fullname: 'Голубев Станислав Борисович',
      mail: 'gra@intei-lada.ru',
      phoneNumber: '+7 812 309 42 20',
      jobTitle: 'Консультант по трейд-ин',
      image: employPhoto,
    },
    {
      fullname: 'Костенко Татьяна Викторовна',
      mail: 'gra@intei-lada.ru',
      phoneNumber: '+7 812 309 42 20',
      jobTitle: 'Ассистент отдела продаж',
      image: employPhoto,
    },
    {
      fullname: 'Гордиенко Владислав Александрович',
      mail: 'gra@intei-lada.ru',
      phoneNumber: '+7 812 309 42 20',
      jobTitle: 'Руководитель отдела продаж',
      image: employPhoto,
    },
    {
      fullname: 'Голубев Станислав Борисович',
      mail: 'gra@intei-lada.ru',
      phoneNumber: '+7 812 309 42 20',
      jobTitle: 'Консультант по трейд-ин',
      image: employPhoto,
    },
    {
      fullname: 'Костенко Татьяна Викторовна',
      mail: 'gra@intei-lada.ru',
      phoneNumber: '+7 812 309 42 20',
      jobTitle: 'Ассистент отдела продаж',
      image: employPhoto,
    },
  ],
};
