import { ISpecificationsArray } from '../types/specifications-types';


export const specificationsArray: ISpecificationsArray[] = [
  {
    carModel: 'LADA Vesta Седан Comfort ',
    power: '90',
    acceleration: '13,6',
    fuelUrbanCycle: '9,8',
    fuelExtraUrbanCycle: '5,9',
    fuelCombinedCycle: '7,3',
    workingCubs: '1596',
    transmissionType: '5MT',
  },
  {
    carModel: 'LADA Vesta Седан Comfort’24',
    power: '122',
    acceleration: '11,6',
    fuelUrbanCycle: '10,1',
    fuelExtraUrbanCycle: '6,3',
    fuelCombinedCycle: '7,7',
    workingCubs: '1774',
    transmissionType: 'AT',
  },
  {
    carModel: 'LADA Vesta Седан Life',
    power: '106',
    acceleration: '11,3',
    fuelUrbanCycle: '9,9',
    fuelExtraUrbanCycle: '5,8',
    fuelCombinedCycle: '7,3',
    workingCubs: '1596',
    transmissionType: '5MT',
  },
  {
    carModel: 'LADA Vesta Седан Life’24',
    power: '122',
    acceleration: '11,6',
    fuelUrbanCycle: '10,1',
    fuelExtraUrbanCycle: '6,3',
    fuelCombinedCycle: '7,7',
    workingCubs: '1774',
    transmissionType: 'AT',
  },
  {
    carModel: 'LADA Vesta Седан Enjoy',
    power: '106',
    acceleration: '11,3',
    fuelUrbanCycle: '9,9',
    fuelExtraUrbanCycle: '5,8',
    fuelCombinedCycle: '7,3',
    workingCubs: '1596',
    transmissionType: '5MT',
  },
  {
    carModel: 'LADA Vesta Седан Enjoy’24',
    power: '122',
    acceleration: '11,6',
    fuelUrbanCycle: '10,1',
    fuelExtraUrbanCycle: '6,3',
    fuelCombinedCycle: '7,7',
    workingCubs: '1774',
    transmissionType: 'AT',
  },
  {
    carModel: 'LADA Vesta Седан Tecno',
    power: '106',
    acceleration: '11,3',
    fuelUrbanCycle: '9,9',
    fuelExtraUrbanCycle: '5,8',
    fuelCombinedCycle: '7,3',
    workingCubs: '1596',
    transmissionType: '5MT',
  },
  {
    carModel: 'LADA Vesta Седан Tecno’24',
    power: '122',
    acceleration: '11,6',
    fuelUrbanCycle: '10,1',
    fuelExtraUrbanCycle: '6,3',
    fuelCombinedCycle: '7,7',
    workingCubs: '1774',
    transmissionType: 'AT',
  },
];
